import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  fr: {
    nav: {
      home: "Accueil",
      movies: "Films",
      series: "Séries",
      trending: "Tendances",
      myList: "Ma liste",
      history: "Historique",
      liked: "Aimés",
      watchLater: "Plus tard",
      channels: "Chaînes TV",
      account: "Mon compte",
      login: "Connexion",
      logout: "Déconnexion",
      register: "S'inscrire",
      admin: "Admin",
      arabwood: "Arabwood",
      hollywood: "Hollywood",
      bollywood: "Bollywood",
      european: "Européen",
      asian: "Asiatique",
      arabicSeries: "Séries Arabes",
      foreignSeries: "Séries Étrangères",
      indianSeries: "Séries Indiennes",
      turkishSeries: "Séries Turques",
      koreanSeries: "Dramas Coréens",
      clips: "Clips",
      songs: "Musique",
      animation: "Dessin",
      quran: "Coran"
    },
    home: {
      title: "Bienvenue sur CineWave",
      subtitle: "Le meilleur du streaming en illimité",
      trending: "Tendances actuelles",
      continueWatching: "Continuer à regarder",
      popularMovies: "Films populaires",
      popularSeries: "Séries populaires",
      watchNow: "Regarder maintenant",
      addToList: "Ajouter à ma liste",
      featured: "À la une",
      recommended: "Recommandés pour vous",
      newReleases: "Nouveautés",
      topRated: "Les mieux notés"
    },
    movie: {
      duration: "Durée",
      year: "Année",
      director: "Réalisateur",
      cast: "Distribution",
      synopsis: "Synopsis",
      genre: "Genre",
      country: "Pays",
      rating: "Note",
      watch: "Regarder",
      trailer: "Bande-annonce",
      share: "Partager",
      added: "Ajouté à ma liste",
      remove: "Retirer de ma liste",
      audio: "Audio",
      subtitles: "Sous-titres",
      episodes: "Épisodes",
      season: "Saison",
      episode: "Épisode",
      nextEpisode: "Épisode suivant",
      previousEpisode: "Épisode précédent",
      oneLanguage: "langue",
      multipleLanguages: "langues",
      subtitlesCount: "sous-titres",
      castMembers: "Distribution",
      languagesAndSubtitles: "Langues et sous-titres",
      audioTracks: "Pistes audio",
      default: "défaut"
    },
    search: {
      placeholder: "Rechercher un film, une série...",
      results: "résultats trouvés",
      noResults: "Aucun résultat trouvé",
      search: "Rechercher",
      popularSearches: "Recherches populaires",
      resultsFor: "Résultats pour"
    },
    channels: {
      title: "Chaînes TV",
      search: "Rechercher une chaîne...",
      noChannels: "Aucune chaîne disponible",
      arabic: "Arabe",
      foreign: "Étrangère",
      sports: "Sports",
      movies: "Films",
      kids: "Enfants",
      religious: "Religieuse",
      music: "Musique",
      news: "Actualités",
      live: "EN DIRECT",
      selectChannel: "Sélectionnez une chaîne pour commencer"
    },
    subscription: {
      title: "Choisissez votre abonnement",
      subtitle: "Profitez de fonctionnalités exclusives",
      free: "Gratuit",
      monthly: "Mensuel",
      yearly: "Annuel",
      lifetime: "À vie",
      priceMonth: "/mois",
      priceYear: "/an",
      features: "Fonctionnalités",
      unlimited: "Visionnage illimité",
      hd: "Qualité HD",
      ultraHD: "Qualité Ultra HD",
      adFree: "Sans publicité",
      download: "Téléchargement",
      devices: "Appareils simultanés",
      support: "Support prioritaire",
      cancel: "Annulation à tout moment",
      subscribe: "S'abonner maintenant",
      currentPlan: "Votre abonnement actuel",
      expires: "Expire le",
      renew: "Renouveler",
      paymentMethod: "Moyen de paiement",
      card: "Carte bancaire",
      paypal: "PayPal"
    },
    common: {
      loading: "Chargement...",
      seeAll: "Voir tout",
      close: "Fermer",
      save: "Enregistrer",
      cancel: "Annuler",
      delete: "Supprimer",
      edit: "Modifier",
      add: "Ajouter",
      back: "Retour",
      next: "Suivant",
      previous: "Précédent",
      play: "Lire",
      pause: "Pause",
      volume: "Volume",
      fullscreen: "Plein écran",
      settings: "Paramètres",
      language: "Langue",
      theme: "Thème",
      dark: "Sombre",
      light: "Clair",
      error: "Une erreur est survenue",
      retry: "Réessayer",
      success: "Opération réussie",
      confirm: "Confirmer",
      details: "Détails",
      all: "Tous",
      additionalInfo: "Informations supplémentaires",
      notFound: "Contenu non trouvé",
      notSpecified: "Non spécifié",
      allGenres: "Tous les genres",
      allYears: "Toutes les années",
      backToArtists: "Retour aux artistes"
    },
    auth: {
      login: "Connexion",
      register: "Inscription",
      email: "Email",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      name: "Nom complet",
      fullName: "Nom complet",
      namePlaceholder: "Ahmed Mohamed",
      forgotPassword: "Mot de passe oublié ?",
      noAccount: "Pas encore de compte ?",
      hasAccount: "Déjà un compte ?",
      loginSuccess: "Connexion réussie",
      registerSuccess: "Inscription réussie",
      logoutSuccess: "Déconnexion réussie",
      invalidCredentials: "Email ou mot de passe incorrect",
      passwordMismatch: "Les mots de passe ne correspondent pas",
      passwordTooShort: "Le mot de passe doit contenir au moins 6 caractères",
      enterCredentials: "Veuillez entrer votre email et mot de passe",
      loginSubtitle: "Connectez-vous pour continuer à regarder",
      registerSubtitle: "Rejoignez des milliers de spectateurs",
      or: "ou",
      demoCredentials: "Informations de connexion de démonstration :",
      newUser: "Nouvel utilisateur",
      agreeTerms: "En vous inscrivant, vous acceptez nos"
    },
    player: {
      play: "Lire",
      pause: "Pause",
      mute: "Muette",
      unmute: "Activer le son",
      speed: "Vitesse",
      quality: "Qualité",
      auto: "Auto",
      skipIntro: "Passer l'intro",
      nextEpisode: "Épisode suivant",
      previousEpisode: "Épisode précédent",
      repeat: "Répéter",
      shuffle: "Aléatoire",
      bookmark: "Ajouter un signet",
      bookmarks: "Signets",
      pictureInPicture: "Image dans l'image",
      theaterMode: "Mode théâtre",
      report: "Signaler un problème",
      subtitlesOff: "Sous-titres désactivés",
      subtitlesOn: "Sous-titres activés",
      audioTrack: "Piste audio",
      playlist: "Liste de lecture"
    },
    admin: {
      dashboard: "Tableau de bord",
      totalMovies: "Total films",
      totalSeries: "Total séries",
      totalUsers: "Total utilisateurs",
      totalRevenue: "Revenus totaux",
      addContent: "Ajouter du contenu",
      editContent: "Modifier le contenu",
      deleteContent: "Supprimer le contenu",
      manageUsers: "Gérer les utilisateurs",
      manageComments: "Gérer les commentaires",
      statistics: "Statistiques",
      backup: "Sauvegarde",
      settings: "Paramètres",
      roles: "Rôles et permissions",
      reports: "Rapports"
    },
    clips: {
      title: "Clips vidéo",
      subtitle: "Les meilleurs clips arabes et internationaux",
      artists: "Artistes",
      favorites: "Favoris",
      myFavorites: "Mes favoris",
      noClips: "Aucun clip disponible",
      noFavorites: "Aucun clip favori",
      addToFavorites: "Ajouter aux favoris",
      removeFromFavorites: "Retirer des favoris",
      views: "vues",
      likes: "j'aime",
      clip: "clip",
      clips: "clips",
      noArtists: "Aucun artiste disponible",
      pop: "Pop",
      rock: "Rock",
      rap: "Rap",
      classical: "Classique",
      jazz: "Jazz",
      arabic: "Arabe",
      indian: "Indien",
      turkish: "Turc",
      like: "J'aime",
      unlike: "Je n'aime plus",
      favorite: "Favori",
      addToFavoritesHint: "Ajoutez vos clips préférés depuis la page des artistes",
      explore: "Explorer les clips"
    },
    songs: {
      title: "Musique",
      artists: "Artistes",
      favorites: "Favoris",
      noSongs: "Aucune chanson disponible",
      noFavorites: "Aucune chanson favorite",
      addToFavorites: "Ajouter aux favoris",
      removeFromFavorites: "Retirer des favoris",
      plays: "écoutes",
      lyrics: "Paroles",
      artist: "Artiste",
      album: "Album",
      duration: "Durée",
      allSongs: "Toutes les chansons",
      songs: "chansons",
      songsInList: "chansons dans votre liste",
      noFavoriteSongs: "Aucune chanson favorite",
      addSongsToFavorites: "Ajoutez vos chansons préférées pour les voir ici",
      exploreSongs: "Explorer la musique",
      favorite: "Favori",
      addedToFavorites: "Ajouté aux favoris",
      removedFromFavorites: "Retiré des favoris"
    },
    quran: {
      title: "Saint Coran",
      reciters: "Récitateurs",
      favorites: "Favoris",
      surahs: "Sourates",
      verses: "versets",
      noReciters: "Aucun récitateur disponible",
      noFavorites: "Aucun récitateur favori",
      addToFavorites: "Ajouter aux favoris",
      removeFromFavorites: "Retirer des favoris",
      listening: "Écoute",
      download: "Télécharger"
    },
    movies: {
      arabicMoviesDescription: "Les derniers et meilleurs films arabes",
      hollywoodDescription: "Les plus grands succès d'Hollywood",
      bollywoodDescription: "Les meilleurs films de Bollywood",
      europeanDescription: "Le meilleur du cinéma européen",
      asianDescription: "Le meilleur du cinéma asiatique",
      moviesCount: "films",
      noMovies: "Aucun film disponible",
      addFromAdmin: "Vous pouvez ajouter de nouveaux films depuis"
    },
    series: {
      arabicSeriesDescription: "Les dernières séries arabes",
      foreignSeriesDescription: "Les meilleures séries internationales",
      indianSeriesDescription: "Les meilleures séries indiennes",
      turkishSeriesDescription: "Les meilleures séries turques",
      koreanSeriesDescription: "Les meilleurs dramas coréens",
      seriesCount: "séries",
      noSeries: "Aucune série disponible",
      addFromAdmin: "Vous pouvez ajouter de nouvelles séries depuis",
      seasons: "saisons",
      episodes: "épisodes",
      latestEpisodes: "Derniers épisodes"
    },
    footer: {
      about: "À propos",
      terms: "Conditions d'utilisation",
      privacy: "Politique de confidentialité",
      contact: "Contact",
      help: "Aide",
      copyright: "© 2024 CineWave. Tous droits réservés."
    }
  },
  en: {
    nav: {
      home: "Home",
      movies: "Movies",
      series: "TV Series",
      trending: "Trending",
      myList: "My List",
      history: "History",
      liked: "Liked",
      watchLater: "Watch Later",
      channels: "TV Channels",
      account: "My Account",
      login: "Login",
      logout: "Logout",
      register: "Sign Up",
      admin: "Admin",
      arabwood: "Arabwood",
      hollywood: "Hollywood",
      bollywood: "Bollywood",
      european: "European",
      asian: "Asian",
      arabicSeries: "Arabic Series",
      foreignSeries: "Foreign Series",
      indianSeries: "Indian Series",
      turkishSeries: "Turkish Series",
      koreanSeries: "Korean Dramas",
      clips: "Music Videos",
      songs: "Music",
      quran: "Quran"
    },
    home: {
      title: "Welcome to CineWave",
      subtitle: "The best unlimited streaming",
      trending: "Trending Now",
      continueWatching: "Continue Watching",
      popularMovies: "Popular Movies",
      popularSeries: "Popular Series",
      watchNow: "Watch Now",
      addToList: "Add to My List",
      featured: "Featured",
      recommended: "Recommended for You",
      newReleases: "New Releases",
      topRated: "Top Rated"
    },
    movie: {
      duration: "Duration",
      year: "Year",
      director: "Director",
      cast: "Cast",
      synopsis: "Synopsis",
      genre: "Genre",
      country: "Country",
      rating: "Rating",
      watch: "Watch",
      trailer: "Trailer",
      share: "Share",
      added: "Added to My List",
      remove: "Remove from My List",
      audio: "Audio",
      subtitles: "Subtitles",
      episodes: "Episodes",
      season: "Season",
      episode: "Episode",
      nextEpisode: "Next Episode",
      previousEpisode: "Previous Episode",
      oneLanguage: "language",
      multipleLanguages: "languages",
      subtitlesCount: "subtitles",
      castMembers: "Cast",
      languagesAndSubtitles: "Languages & Subtitles",
      audioTracks: "Audio tracks",
      default: "default"
    },
    search: {
      placeholder: "Search for a movie, series...",
      results: "results found",
      noResults: "No results found",
      search: "Search",
      popularSearches: "Popular Searches",
      resultsFor: "Results for"
    },
    channels: {
      title: "TV Channels",
      search: "Search for a channel...",
      noChannels: "No channels available",
      arabic: "Arabic",
      foreign: "Foreign",
      sports: "Sports",
      movies: "Movies",
      kids: "Kids",
      religious: "Religious",
      music: "Music",
      news: "News",
      live: "LIVE",
      selectChannel: "Select a channel to start"
    },
    subscription: {
      title: "Choose Your Plan",
      subtitle: "Enjoy exclusive features",
      free: "Free",
      monthly: "Monthly",
      yearly: "Yearly",
      lifetime: "Lifetime",
      priceMonth: "/month",
      priceYear: "/year",
      features: "Features",
      unlimited: "Unlimited streaming",
      hd: "HD Quality",
      ultraHD: "Ultra HD Quality",
      adFree: "Ad-free experience",
      download: "Download content",
      devices: "Simultaneous devices",
      support: "Priority support",
      cancel: "Cancel anytime",
      subscribe: "Subscribe Now",
      currentPlan: "Your Current Plan",
      expires: "Expires on",
      renew: "Renew",
      paymentMethod: "Payment Method",
      card: "Credit Card",
      paypal: "PayPal"
    },
    common: {
      loading: "Loading...",
      seeAll: "See All",
      close: "Close",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      back: "Back",
      next: "Next",
      previous: "Previous",
      play: "Play",
      pause: "Pause",
      volume: "Volume",
      fullscreen: "Fullscreen",
      settings: "Settings",
      language: "Language",
      theme: "Theme",
      dark: "Dark",
      light: "Light",
      error: "An error occurred",
      retry: "Retry",
      success: "Success",
      confirm: "Confirm",
      details: "Details",
      all: "All",
      additionalInfo: "Additional information",
      notFound: "Content not found",
      notSpecified: "Not specified",
      allGenres: "All Genres",
      allYears: "All Years",
      backToArtists: "Back to Artists"
    },
    auth: {
      login: "Login",
      register: "Sign Up",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      name: "Full Name",
      fullName: "Full Name",
      namePlaceholder: "Ahmed Mohamed",
      forgotPassword: "Forgot Password?",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      loginSuccess: "Login successful",
      registerSuccess: "Registration successful",
      logoutSuccess: "Logout successful",
      invalidCredentials: "Invalid email or password",
      passwordMismatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 6 characters",
      enterCredentials: "Please enter your email and password",
      loginSubtitle: "Login to continue watching",
      registerSubtitle: "Join thousands of viewers",
      or: "or",
      demoCredentials: "Demo login credentials:",
      newUser: "New User",
      agreeTerms: "By signing up, you agree to our"
    },
    player: {
      play: "Play",
      pause: "Pause",
      mute: "Mute",
      unmute: "Unmute",
      speed: "Speed",
      quality: "Quality",
      auto: "Auto",
      skipIntro: "Skip Intro",
      nextEpisode: "Next Episode",
      previousEpisode: "Previous Episode",
      repeat: "Repeat",
      shuffle: "Shuffle",
      bookmark: "Add Bookmark",
      bookmarks: "Bookmarks",
      pictureInPicture: "Picture in Picture",
      theaterMode: "Theater Mode",
      report: "Report an issue",
      subtitlesOff: "Subtitles Off",
      subtitlesOn: "Subtitles On",
      audioTrack: "Audio Track",
      playlist: "Playlist"
    },
    admin: {
      dashboard: "Dashboard",
      totalMovies: "Total Movies",
      totalSeries: "Total Series",
      totalUsers: "Total Users",
      totalRevenue: "Total Revenue",
      addContent: "Add Content",
      editContent: "Edit Content",
      deleteContent: "Delete Content",
      manageUsers: "Manage Users",
      manageComments: "Manage Comments",
      statistics: "Statistics",
      backup: "Backup",
      settings: "Settings",
      roles: "Roles & Permissions",
      reports: "Reports"
    },
    clips: {
      title: "Music Videos",
      subtitle: "The best Arabic and international music videos",
      artists: "Artists",
      favorites: "Favorites",
      myFavorites: "My Favorites",
      noClips: "No clips available",
      noFavorites: "No favorite clips",
      addToFavorites: "Add to Favorites",
      removeFromFavorites: "Remove from Favorites",
      views: "views",
      likes: "likes",
      clip: "clip",
      clips: "clips",
      noArtists: "No artists available",
      pop: "Pop",
      rock: "Rock",
      rap: "Rap",
      classical: "Classical",
      jazz: "Jazz",
      arabic: "Arabic",
      indian: "Indian",
      turkish: "Turkish",
      like: "Like",
      unlike: "Unlike",
      favorite: "Favorite",
      addToFavoritesHint: "Add your favorite clips from the artists page",
      explore: "Explore Clips"
    },
    songs: {
      title: "Music",
      artists: "Artists",
      favorites: "Favorites",
      noSongs: "No songs available",
      noFavorites: "No favorite songs",
      addToFavorites: "Add to Favorites",
      removeFromFavorites: "Remove from Favorites",
      plays: "plays",
      lyrics: "Lyrics",
      artist: "Artist",
      album: "Album",
      duration: "Duration",
      allSongs: "All Songs",
      songs: "songs",
      songsInList: "songs in your list",
      noFavoriteSongs: "No favorite songs",
      addSongsToFavorites: "Add your favorite songs to see them here",
      exploreSongs: "Explore Music",
      favorite: "Favorite",
      addedToFavorites: "Added to favorites",
      removedFromFavorites: "Removed from favorites"
    },
    quran: {
      title: "Holy Quran",
      reciters: "Reciters",
      favorites: "Favorites",
      surahs: "Surahs",
      verses: "verses",
      noReciters: "No reciters available",
      noFavorites: "No favorite reciters",
      addToFavorites: "Add to Favorites",
      removeFromFavorites: "Remove from Favorites",
      listening: "Listening",
      download: "Download"
    },
    movies: {
      arabicMoviesDescription: "Latest and greatest Arabic movies",
      hollywoodDescription: "Hollywood's biggest hits",
      bollywoodDescription: "Best of Bollywood cinema",
      europeanDescription: "Best of European cinema",
      asianDescription: "Best of Asian cinema",
      moviesCount: "movies",
      noMovies: "No movies available",
      addFromAdmin: "You can add new movies from"
    },
    series: {
      arabicSeriesDescription: "Latest Arabic series",
      foreignSeriesDescription: "Best international series",
      indianSeriesDescription: "Best Indian series",
      turkishSeriesDescription: "Best Turkish series",
      koreanSeriesDescription: "Best Korean dramas",
      seriesCount: "series",
      noSeries: "No series available",
      addFromAdmin: "You can add new series from",
      seasons: "seasons",
      episodes: "episodes",
      latestEpisodes: "Latest Episodes"
    },
    footer: {
      about: "About",
      terms: "Terms of Use",
      privacy: "Privacy Policy",
      contact: "Contact",
      help: "Help",
      copyright: "© 2024 CineWave. All rights reserved."
    }
  },
  ar: {
    nav: {
      home: "الرئيسية",
      movies: "أفلام",
      series: "مسلسلات",
      trending: "الأكثر مشاهدة",
      myList: "قائمتي",
      history: "سجل المشاهدة",
      liked: "المعجبة",
      watchLater: "مشاهدة لاحقاً",
      channels: "القنوات",
      account: "حسابي",
      login: "تسجيل الدخول",
      logout: "تسجيل الخروج",
      register: "إنشاء حساب",
      admin: "المشرف",
      arabwood: "العربية",
      hollywood: "هوليود",
      bollywood: "بوليوود",
      european: "الأوروبية",
      asian: "الآسيوية",
      arabicSeries: "مسلسلات عربية",
      foreignSeries: "مسلسلات أجنبية",
      indianSeries: "مسلسلات هندية",
      turkishSeries: "مسلسلات تركية",
      koreanSeries: "دراما كورية",
      clips: "كليبات",
      songs: "أغاني",
      quran: "القرآن"
    },
    home: {
      title: "مرحباً بك في CineWave",
      subtitle: "أفضل منصة للمشاهدة غير المحدودة",
      trending: "الأكثر مشاهدة الآن",
      continueWatching: "أكمل المشاهدة",
      popularMovies: "أفلام شعبية",
      popularSeries: "مسلسلات شعبية",
      watchNow: "شاهد الآن",
      addToList: "أضف لقائمتي",
      featured: "مميز",
      recommended: "موصى لك",
      newReleases: "الإصدارات الجديدة",
      topRated: "الأعلى تقييماً"
    },
    movie: {
      duration: "المدة",
      year: "السنة",
      director: "المخرج",
      cast: "طاقم التمثيل",
      synopsis: "القصة",
      genre: "التصنيف",
      country: "الدولة",
      rating: "التقييم",
      watch: "مشاهدة",
      trailer: "الإعلان",
      share: "مشاركة",
      added: "تمت الإضافة لقائمتي",
      remove: "إزالة من قائمتي",
      audio: "الصوت",
      subtitles: "الترجمة",
      episodes: "الحلقات",
      season: "الموسم",
      episode: "الحلقة",
      nextEpisode: "الحلقة التالية",
      previousEpisode: "الحلقة السابقة",
      oneLanguage: "لغة",
      multipleLanguages: "لغات",
      subtitlesCount: "ترجمة",
      castMembers: "طاقم التمثيل",
      languagesAndSubtitles: "اللغات والترجمات",
      audioTracks: "المسارات الصوتية",
      default: "افتراضي"
    },
    search: {
      placeholder: "ابحث عن فيلم، مسلسل...",
      results: "نتيجة تم العثور عليها",
      noResults: "لم يتم العثور على نتائج",
      search: "بحث",
      popularSearches: "عمليات البحث الشائعة",
      resultsFor: "نتائج البحث عن"
    },
    channels: {
      title: "القنوات التلفزيونية",
      search: "ابحث عن قناة...",
      noChannels: "لا توجد قنوات متاحة",
      arabic: "عربية",
      foreign: "أجنبية",
      sports: "رياضية",
      movies: "أفلام",
      kids: "أطفال",
      religious: "دينية",
      music: "موسيقى",
      news: "أخبار",
      live: "مباشر",
      selectChannel: "اختر قناة للبدء"
    },
    subscription: {
      title: "اختر باقتك",
      subtitle: "استمتع بميزات حصرية",
      free: "مجاني",
      monthly: "شهري",
      yearly: "سنوي",
      lifetime: "مدى الحياة",
      priceMonth: "/شهر",
      priceYear: "/سنة",
      features: "المميزات",
      unlimited: "مشاهدة غير محدودة",
      hd: "جودة HD",
      ultraHD: "جودة فائقة",
      adFree: "بدون إعلانات",
      download: "تحميل المحتوى",
      devices: "أجهزة متزامنة",
      support: "دعم أولوية",
      cancel: "إلغاء في أي وقت",
      subscribe: "اشترك الآن",
      currentPlan: "باقتك الحالية",
      expires: "تنتهي في",
      renew: "تجديد",
      paymentMethod: "طريقة الدفع",
      card: "بطاقة ائتمان",
      paypal: "باي بال"
    },
    common: {
      loading: "جاري التحميل...",
      seeAll: "عرض الكل",
      close: "إغلاق",
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      add: "إضافة",
      back: "رجوع",
      next: "التالي",
      previous: "السابق",
      play: "تشغيل",
      pause: "إيقاف",
      volume: "مستوى الصوت",
      fullscreen: "شاشة كاملة",
      settings: "الإعدادات",
      language: "اللغة",
      theme: "المظهر",
      dark: "داكن",
      light: "فاتح",
      error: "حدث خطأ",
      retry: "إعادة المحاولة",
      success: "تمت العملية بنجاح",
      confirm: "تأكيد",
      details: "التفاصيل",
      all: "الكل",
      additionalInfo: "معلومات إضافية",
      notFound: "المحتوى غير موجود",
      notSpecified: "غير محدد",
      allGenres: "كل التصنيفات",
      allYears: "كل السنوات",
      backToArtists: "العودة للفنانين"
    },
    auth: {
      login: "تسجيل الدخول",
      register: "إنشاء حساب",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      name: "الاسم الكامل",
      fullName: "الاسم الكامل",
      namePlaceholder: "أحمد محمد",
      forgotPassword: "نسيت كلمة المرور؟",
      noAccount: "ليس لديك حساب؟",
      hasAccount: "لديك حساب بالفعل؟",
      loginSuccess: "تم تسجيل الدخول بنجاح",
      registerSuccess: "تم إنشاء الحساب بنجاح",
      logoutSuccess: "تم تسجيل الخروج بنجاح",
      invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
      passwordMismatch: "كلمة المرور غير متطابقة",
      passwordTooShort: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
      enterCredentials: "الرجاء إدخال البريد الإلكتروني وكلمة المرور",
      loginSubtitle: "سجل دخولك لمتابعة المشاهدة",
      registerSubtitle: "انضم إلى آلاف المشاهدين",
      or: "أو",
      demoCredentials: "بيانات تسجيل الدخول التجريبية:",
      newUser: "مستخدم جديد",
      agreeTerms: "بالتسجيل فإنك توافق على"
    },
    player: {
      play: "تشغيل",
      pause: "إيقاف",
      mute: "كتم الصوت",
      unmute: "إلغاء كتم الصوت",
      speed: "السرعة",
      quality: "الجودة",
      auto: "تلقائي",
      skipIntro: "تخطي المقدمة",
      nextEpisode: "الحلقة التالية",
      previousEpisode: "الحلقة السابقة",
      repeat: "تكرار",
      shuffle: "عشوائي",
      bookmark: "إضافة إشارة مرجعية",
      bookmarks: "الإشارات المرجعية",
      pictureInPicture: "صورة داخل صورة",
      theaterMode: "وضع المسرح",
      report: "الإبلاغ عن مشكلة",
      subtitlesOff: "إيقاف الترجمة",
      subtitlesOn: "تشغيل الترجمة",
      audioTrack: "المسار الصوتي",
      playlist: "قائمة التشغيل"
    },
    admin: {
      dashboard: "لوحة التحكم",
      totalMovies: "إجمالي الأفلام",
      totalSeries: "إجمالي المسلسلات",
      totalUsers: "إجمالي المستخدمين",
      totalRevenue: "إجمالي الإيرادات",
      addContent: "إضافة محتوى",
      editContent: "تعديل محتوى",
      deleteContent: "حذف محتوى",
      manageUsers: "إدارة المستخدمين",
      manageComments: "إدارة التعليقات",
      statistics: "الإحصائيات",
      backup: "النسخ الاحتياطي",
      settings: "الإعدادات",
      roles: "الأدوار والصلاحيات",
      reports: "التقارير"
    },
    clips: {
      title: "الكليبات",
      subtitle: "أحدث وأجمل الكليبات العربية والعالمية",
      artists: "الفنانين",
      favorites: "المفضلة",
      myFavorites: "مفضلاتي",
      noClips: "لا توجد كليبات متاحة",
      noFavorites: "لا توجد كليبات مفضلة",
      addToFavorites: "أضف إلى المفضلة",
      removeFromFavorites: "أزل من المفضلة",
      views: "مشاهدة",
      likes: "إعجاب",
      clip: "كليب",
      clips: "كليبات",
      noArtists: "لا توجد فنانين",
      pop: "بوب",
      rock: "روك",
      rap: "راب",
      classical: "كلاسيكي",
      jazz: "جاز",
      arabic: "عربي",
      indian: "هندي",
      turkish: "تركي",
      like: "إعجاب",
      unlike: "إلغاء الإعجاب",
      favorite: "مفضلة",
      addToFavoritesHint: "أضف كليباتك المفضلة من صفحة الفنانين",
      explore: "استكشف الكليبات"
    },
    songs: {
      title: "الأغاني",
      artists: "الفنانين",
      favorites: "المفضلة",
      noSongs: "لا توجد أغاني متاحة",
      noFavorites: "لا توجد أغاني مفضلة",
      addToFavorites: "أضف إلى المفضلة",
      removeFromFavorites: "أزل من المفضلة",
      plays: "استماع",
      lyrics: "كلمات الأغنية",
      artist: "الفنان",
      album: "الألبوم",
      duration: "المدة",
      allSongs: "جميع الأغاني",
      songs: "أغنية",
      songsInList: "أغنية في قائمتك",
      noFavoriteSongs: "لا توجد أغاني مفضلة",
      addSongsToFavorites: "أضف الأغاني التي تحبها إلى المفضلة لتظهر هنا",
      exploreSongs: "استكشاف الأغاني",
      favorite: "مفضلة",
      addedToFavorites: "تم إضافة الأغنية إلى المفضلة",
      removedFromFavorites: "تم إزالة الأغنية من المفضلة"
    },
    quran: {
      title: "القرآن الكريم",
      reciters: "القراء",
      favorites: "المفضلون",
      surahs: "السور",
      verses: "آية",
      noReciters: "لا توجد قراء متاحون",
      noFavorites: "لا توجد قراء مفضلين",
      addToFavorites: "أضف إلى المفضلين",
      removeFromFavorites: "أزل من المفضلين",
      listening: "استماع",
      download: "تحميل"
    },
    movies: {
      arabicMoviesDescription: "أحدث وأهم الأفلام العربية",
      hollywoodDescription: "أكبر نجاحات هوليود",
      bollywoodDescription: "أفضل أفلام بوليوود",
      europeanDescription: "أفضل الأفلام الأوروبية",
      asianDescription: "أفضل الأفلام الآسيوية",
      moviesCount: "فيلم",
      noMovies: "لا توجد أفلام حالياً",
      addFromAdmin: "يمكنك إضافة أفلام جديدة من"
    },
    series: {
      arabicSeriesDescription: "أحدث المسلسلات العربية",
      foreignSeriesDescription: "أفضل المسلسلات العالمية",
      indianSeriesDescription: "أفضل المسلسلات الهندية",
      turkishSeriesDescription: "أفضل المسلسلات التركية",
      koreanSeriesDescription: "أفضل الدراما الكورية",
      seriesCount: "مسلسل",
      noSeries: "لا توجد مسلسلات حالياً",
      addFromAdmin: "يمكنك إضافة مسلسلات جديدة من",
      seasons: "مواسم",
      episodes: "حلقات",
      latestEpisodes: "أحدث الحلقات"
    },
    footer: {
      about: "عن المنصة",
      terms: "شروط الاستخدام",
      privacy: "سياسة الخصوصية",
      contact: "اتصل بنا",
      help: "المساعدة",
      copyright: "© 2024 CineWave. جميع الحقوق محفوظة"
    }
  }
};

// ========== HOOKS ==========
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// ========== PROVIDER ==========
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'fr';
  });

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value?.[k] === undefined) {
        return key;
      }
      value = value[k];
    }
    return value;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    const isRTL = lang === 'ar';
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    document.body.style.direction = isRTL ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    const isRTL = language === 'ar';
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.body.style.direction = isRTL ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};